-- Este arquivo documenta o DDL (Data Definition Language) do projeto.
-- Os comandos foram gerados automaticamente pelo Django ORM 
-- usando o comando 'manage.py sqlmigrate' para cada app.
-- Data da Geração: 2025-11-25

-- ==========================================
-- APP: PRODUTO (Catálogo)
-- ==========================================
BEGIN;
CREATE TABLE "produto_categoria" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "nome" varchar(100) NOT NULL UNIQUE, 
    "descricao" text NULL
);

CREATE TABLE "produto_produto" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "codigo_barras" varchar(13) NOT NULL UNIQUE, 
    "nome" varchar(100) NOT NULL, 
    "descricao" text NULL, 
    "tipo_produto" varchar(10) NOT NULL, 
    "esta_ativo" boolean NOT NULL, 
    "categoria_id" bigint NULL
);
-- Indices e Constraints
CREATE INDEX "produto_categoria_nome_like" ON "produto_categoria" ("nome" varchar_pattern_ops);
ALTER TABLE "produto_produto" ADD CONSTRAINT "produto_produto_categoria_id_fk_produto_categoria_id" FOREIGN KEY ("categoria_id") REFERENCES "produto_categoria" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "produto_produto_codigo_barras_like" ON "produto_produto" ("codigo_barras" varchar_pattern_ops);
CREATE INDEX "produto_produto_categoria_id" ON "produto_produto" ("categoria_id");
COMMIT;

-- ==========================================
-- APP: FILIAL
-- ==========================================
BEGIN;
CREATE TABLE "filial_filial" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "nome" varchar(100) NOT NULL UNIQUE, 
    "cep" varchar(9) NOT NULL, 
    "logradouro" varchar(255) NOT NULL, 
    "cidade" varchar(100) NOT NULL, 
    "estado" varchar(2) NOT NULL, 
    "gerente_id" integer NULL UNIQUE, 
    "esta_ativa" boolean NOT NULL
);
CREATE INDEX "filial_filial_nome_like" ON "filial_filial" ("nome" varchar_pattern_ops);
COMMIT;

-- ==========================================
-- APP: USUARIO (Perfil Local)
-- ==========================================
BEGIN;
CREATE TABLE "usuario_perfilusuario" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "usuario_id_auth" integer NOT NULL UNIQUE, 
    "nome_completo" varchar(255) NOT NULL, 
    "cpf" varchar(14) NOT NULL UNIQUE, 
    "cargo" varchar(20) NOT NULL, 
    "ativo" boolean NOT NULL, 
    "filial_id" bigint NULL
);
ALTER TABLE "usuario_perfilusuario" ADD CONSTRAINT "usuario_perfilusuario_filial_id_fk_filial_filial_id" FOREIGN KEY ("filial_id") REFERENCES "filial_filial" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "usuario_perfilusuario_cpf_like" ON "usuario_perfilusuario" ("cpf" varchar_pattern_ops);
CREATE INDEX "usuario_perfilusuario_filial_id" ON "usuario_perfilusuario" ("filial_id");
COMMIT;

-- ==========================================
-- APP: ESTOQUE
-- ==========================================
BEGIN;
CREATE TABLE "estoque_itemestoque" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "quantidade_atual" double precision NOT NULL, 
    "preco_venda_atual" numeric(10, 2) NOT NULL, 
    "quantidade_minima_estoque" double precision NOT NULL, 
    "filial_id" bigint NOT NULL, 
    "produto_id" bigint NOT NULL
);
-- Constraints
ALTER TABLE "estoque_itemestoque" ADD CONSTRAINT "estoque_itemestoque_produto_id_filial_id_uniq" UNIQUE ("produto_id", "filial_id");
ALTER TABLE "estoque_itemestoque" ADD CONSTRAINT "estoque_itemestoque_filial_id_fk_filial_filial_id" FOREIGN KEY ("filial_id") REFERENCES "filial_filial" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "estoque_itemestoque" ADD CONSTRAINT "estoque_itemestoque_produto_id_fk_produto_produto_id" FOREIGN KEY ("produto_id") REFERENCES "produto_produto" ("id") DEFERRABLE INITIALLY DEFERRED;
-- Indices
CREATE INDEX "estoque_itemestoque_filial_id" ON "estoque_itemestoque" ("filial_id");
CREATE INDEX "estoque_itemestoque_produto_id" ON "estoque_itemestoque" ("produto_id");
COMMIT;

-- ==========================================
-- APP: VENDA
-- ==========================================
BEGIN;
CREATE TABLE "venda_venda" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "usuario_id" integer NOT NULL, 
    "data_venda" timestamp with time zone NOT NULL, 
    "status" varchar(20) NOT NULL, 
    "forma_pagamento" varchar(20) NULL, 
    "valor_total" numeric(10, 2) NOT NULL, 
    "filial_id" bigint NOT NULL
);

CREATE TABLE "venda_itemvenda" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "quantidade_vendida" double precision NOT NULL, 
    "preco_vendido" numeric(10, 2) NOT NULL, 
    "produto_id" bigint NOT NULL, 
    "venda_id" bigint NOT NULL
);

-- Constraints Venda
ALTER TABLE "venda_venda" ADD CONSTRAINT "venda_venda_filial_id_fk_filial_filial_id" FOREIGN KEY ("filial_id") REFERENCES "filial_filial" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "venda_venda_filial_id" ON "venda_venda" ("filial_id");

-- Constraints ItemVenda
ALTER TABLE "venda_itemvenda" ADD CONSTRAINT "venda_itemvenda_produto_id_fk_produto_produto_id" FOREIGN KEY ("produto_id") REFERENCES "produto_produto" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "venda_itemvenda" ADD CONSTRAINT "venda_itemvenda_venda_id_fk_venda_venda_id" FOREIGN KEY ("venda_id") REFERENCES "venda_venda" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "venda_itemvenda_produto_id" ON "venda_itemvenda" ("produto_id");
CREATE INDEX "venda_itemvenda_venda_id" ON "venda_itemvenda" ("venda_id");
COMMIT;
